#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 22, 2017 12:34:11 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import LoginSupport

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Account (root)
    LoginSupport.init(root, top)
    root.mainloop()

w = None
def create_Account(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Account (w)
    LoginSupport.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Account():
    global w
    w.destroy()
    w = None


class Account:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("800x719+365+67")
        top.title("Account")
        top.configure(background="#93d993")
        root.resizable(False, False)



        self.AcBtnRet = Button(top)
        self.AcBtnRet.place(relx=0.03, rely=0.14, height=26, width=121)
        self.AcBtnRet.configure(activebackground="#d9d9d9")
        self.AcBtnRet.configure(background="#2cd900")
        self.AcBtnRet.configure(text='''Return to home''')

        self.AccListBox = Listbox(top)
        self.AccListBox.place(relx=0.01, rely=0.32, relheight=0.69
                , relwidth=0.97)
        self.AccListBox.configure(background="#68d9c3")
        self.AccListBox.configure(font="TkFixedFont")
        self.AccListBox.configure(width=774)

        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.21, relheight=0.1, relwidth=0.97)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#68d9c3")
        self.Frame1.configure(width=775)

        self.AccMoneyLabel = Label(self.Frame1)
        self.AccMoneyLabel.place(relx=0.74, rely=0.4, height=18, width=200)
        self.AccMoneyLabel.configure(background="#68d9c3")
        self.AccMoneyLabel.configure(text='''$0.00''')
        self.AccMoneyLabel.configure(width=106)

        self.AccNameLabel = Label(self.Frame1)
        self.AccNameLabel.place(relx=0.39, rely=0.4, height=18, width=92)
        self.AccNameLabel.configure(background="#68d9c3")
        self.AccNameLabel.configure(text='''Account name''')







if __name__ == '__main__':
    vp_start_gui()


