#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 26, 2017 12:02:50 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import _support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = ForgotInfo (root)
    _support.init(root, top)
    root.mainloop()

w = None
def create_ForgotInfo(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = ForgotInfo (w)
    _support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_ForgotInfo():
    global w
    w.destroy()
    w = None


class ForgotInfo:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("800x719+713+91")
        top.title("recover account")
        top.configure(background="#91d98c")



        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.34, rely=0.29, relheight=0.04, relwidth=0.31)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Entry2 = Entry(top)
        self.Entry2.place(relx=0.34, rely=0.4, relheight=0.04, relwidth=0.31)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.Button1 = Button(top)
        self.Button1.place(relx=0.34, rely=0.49, height=42, width=138)
        self.Button1.configure(activebackground="#2cd900")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#2cd900")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Recover account''')
        self.Button1.configure(width=138)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.34, rely=0.24, height=31, width=57)
        self.Label1.configure(background="#91d98c")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Name''')
        self.Label1.configure(width=57)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.34, rely=0.35, height=31, width=48)
        self.Label2.configure(background="#91d98c")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Email''')






if __name__ == '__main__':
    vp_start_gui()

