#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 22, 2017 01:27:32 PM
import sys
import Main
from tkinter import messagebox
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import LoginSupport

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = NewCustomer (root)
    LoginSupport.init(root, top)
    root.mainloop()

w = None
def create_NewCustomer(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = NewCustomer (w)
    LoginSupport.init(w, top)
    return (w, top)

def destroy_NewCustomer():
    global w
    w.destroy()
    w = None


class NewCustomer:

    def Submit(self):
        name = self.SeNameBox.get()
        address = self.SeAddressBox.get()
        city = self.SeCityBox.get()
        state = self.SeStateBox.get()
        zip = self.SeZipBox.get()
        country = self.SeCountryBox.get()
        phone = self.SePhoneBox.get()
        password = self.SePassBox.get()
        passwordConf = self.SePassConfBox.get()
        if (len(name) == 0 or len(address) == 0 or len(city) == 0 or len(state) == 0 \
                    or len(zip) == 0 or len(country) == 0 or len(phone) == 0 or len(password) == 0 \
                    or len(passwordConf) == 0):
            print("stuff")
            messagebox.showinfo("Error", "No field can be left empty.")
        elif(password != passwordConf):
            messagebox.showinfo("Error", "The passwords do not match.")
        else:
            # get highest customer id from database and increment it by one.
            #assign them the new id and submit into sql the customer information with the new id.
            #print message telling them what their id is
            LoginSupport.destroy_window()
            Main.vp_start_gui()

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("800x719+365+67")
        top.title("New Customer")
        top.configure(background="#93d993")



        self.SeNameBox = Entry(top)
        self.SeNameBox.place(relx=0.1, rely=0.1, relheight=0.03, relwidth=0.46)
        self.SeNameBox.configure(background="white")
        self.SeNameBox.configure(font="TkFixedFont")
        self.SeNameBox.configure(width=366)


        self.SeAddressBox = Entry(top)
        self.SeAddressBox.place(relx=0.1, rely=0.18, relheight=0.03
                , relwidth=0.62)
        self.SeAddressBox.configure(background="white")
        self.SeAddressBox.configure(font="TkFixedFont")
        self.SeAddressBox.configure(width=496)

        self.SeCityBox = Entry(top)
        self.SeCityBox.place(relx=0.1, rely=0.24, relheight=0.03, relwidth=0.2)
        self.SeCityBox.configure(background="white")
        self.SeCityBox.configure(font="TkFixedFont")
        self.SeCityBox.configure(width=156)

        self.SeZipBox = Entry(top)
        self.SeZipBox.place(relx=0.43, rely=0.24, relheight=0.03, relwidth=0.11)
        self.SeZipBox.configure(background="white")
        self.SeZipBox.configure(font="TkFixedFont")
        self.SeZipBox.configure(width=86)

        self.SeStateBox = Entry(top)
        self.SeStateBox.place(relx=0.33, rely=0.24, relheight=0.03
                , relwidth=0.07)
        self.SeStateBox.configure(background="white")
        self.SeStateBox.configure(font="TkFixedFont")
        self.SeStateBox.configure(width=56)


        self.SePhoneBox = Entry(top)
        self.SePhoneBox.place(relx=0.1, rely=0.32, relheight=0.03, relwidth=0.18)

        self.SePhoneBox.configure(background="white")
        self.SePhoneBox.configure(font="TkFixedFont")

        self.SePassConfBox = Entry(top)
        self.SePassConfBox.place(relx=0.1, rely=0.45, relheight=0.03
                , relwidth=0.18)
        self.SePassConfBox.configure(background="white")
        self.SePassConfBox.configure(font="TkFixedFont")

        self.SeCountryBox = Entry(top)
        self.SeCountryBox.place(relx=0.57, rely=0.24, relheight=0.03
                , relwidth=0.18)
        self.SeCountryBox.configure(background="white")
        self.SeCountryBox.configure(font="TkFixedFont")

        self.SePassBox = Entry(top)
        self.SePassBox.place(relx=0.1, rely=0.38, relheight=0.03, relwidth=0.18)
        self.SePassBox.configure(background="white")
        self.SePassBox.configure(font="TkFixedFont")

        self.Label1 = Label(top)
        self.Label1.place(relx=0.1, rely=0.07, height=18, width=39)
        self.Label1.configure(background="#93d993")
        self.Label1.configure(text='''Name''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.1, rely=0.15, height=18, width=40)
        self.Label2.configure(background="#93d993")
        self.Label2.configure(text='''Address''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.1, rely=0.21, height=18, width=27)
        self.Label3.configure(background="#93d993")
        self.Label3.configure(text='''City''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.33, rely=0.21, height=18, width=36)
        self.Label4.configure(background="#93d993")
        self.Label4.configure(text='''State''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.43, rely=0.21, height=18, width=23)
        self.Label5.configure(background="#93d993")
        self.Label5.configure(text='''Zip''')

        self.Label6 = Label(top)
        self.Label6.place(relx=0.57, rely=0.21, height=18, width=52)
        self.Label6.configure(background="#93d993")
        self.Label6.configure(text='''Country''')

        self.Label7 = Label(top)
        self.Label7.place(relx=0.1, rely=0.29, height=18, width=41)
        self.Label7.configure(background="#93d993")
        self.Label7.configure(text='''Phone''')

        self.Label8 = Label(top)
        self.Label8.place(relx=0.1, rely=0.35, height=18, width=60)
        self.Label8.configure(background="#93d993")
        self.Label8.configure(text='''Password''')

        self.Label9 = Label(top)
        self.Label9.place(relx=0.1, rely=0.42, height=18, width=112)
        self.Label9.configure(background="#93d993")
        self.Label9.configure(text='''Confirm password''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.1, rely=0.53, height=26, width=200)
        self.Button1.configure(activebackground="#d9d91c")
        self.Button1.configure(background="#2cd900")
        self.Button1.configure(text='''Submit''')
        self.Button1.configure(command= self.Submit)







if __name__ == '__main__':
    vp_start_gui()


